### PR TITLE
Chris/Update to dev server

### PR DESCRIPTION
**Pull request by ckdesir**
<p align="center"></p>

## Overview
Some final changes before launch

## Changes Made

- [x] Change package name (then across files just for consistency)
- [x] Add NSFW filter + update schema
- [x] Change social query
- [x] Add new app icon

## Screenshots
<details>
 <summary>NSFW Example
 </summary>

<p float="left">
  
</p>
</details>

### CODE REVIEW

**Review by kevinsun-dev — CHANGES_REQUESTED** [review]
Ah, actually you can just change the applicationId in Gradle and it will work, no package finagling required (though honestly, yeah, com.example looks terrible). Also, historically we're com.cornellappdev.app. In this case. `com.cornellappdev.volume` is all we need, since it's quite clear that this is an Android app. This will also be the url for Google Play, so let's keep it consistant.

**Comment by ckdesir** [comment]
> 
> 
> Ah, actually you can just change the applicationId in Gradle and it will work, no package finagling required (though honestly, yeah, com.example looks terrible). Also, historically we're com.cornellappdev.app. In this case. `com.cornellappdev.volume` is all we need, since it's quite clear that this is an Android app. This will also be the url for Google Play, so let's keep it consistant.

Aastha told me she uploaded the old package as this, will changing it be okay?

**Comment by kevinsun-dev** [comment]
> > Ah, actually you can just change the applicationId in Gradle and it will work, no package finagling required (though honestly, yeah, com.example looks terrible). Also, historically we're com.cornellappdev.app. In this case. `com.cornellappdev.volume` is all we need, since it's quite clear that this is an Android app. This will also be the url for Google Play, so let's keep it consistant.
> 
> Aastha told me she uploaded the old package as this, will changing it be okay?

As long as it's not yet public on the Play Store, perfectly fine. If it was already uploaded to the Play Store, we can create a new app listing and delete the old one if we haven't yet advertised with the old URL.

**Review by kevinsun-dev — APPROVED** [review]
LGTM

**Pull request merged**
